import io

import qrcode
from fpdf import FPDF
from unidecode import unidecode

from .db import display_id


def _pdf_safe(value) -> str:
    # The built-in Helvetica core font only supports Latin-1/WinAnsi --
    # any character outside that (e.g. CJK in a patient's name) raises
    # FPDFUnicodeEncodingException and crashes report generation. Rather
    # than bundling a multi-MB Unicode font just to avoid a crash,
    # transliterate to the closest ASCII representation so the report
    # always renders, even if non-Latin names lose their original glyphs.
    return unidecode(str(value))

RECOMMENDATIONS = {
    "Low Risk": "Continue healthy lifestyle habits and schedule routine annual check-ups. This is a lifestyle-based screening, so keeping up regular check-ups is still the best way to stay ahead of any changes.",
    "High Risk": "Discuss modifiable risk factors with a physician and consider a full cognitive workup. This result does not mean the person has or will develop dementia.",
    "Nondemented": "This screening did not flag signs of cognitive decline. Continue routine monitoring; this result does not rule out dementia.",
    "Demented": "This screening's findings are consistent with the Demented classification, not a diagnosis. Refer to a neurologist for a full diagnostic workup.",
    "Converted": "This screening flagged a pattern consistent with transition between cognitive stages, not a diagnosis. Recommend closer follow-up and repeat imaging.",
}


def _build_qr_image(payload: str):
    qr = qrcode.QRCode(box_size=6, border=2)
    qr.add_data(payload)
    qr.make(fit=True)
    return qr.make_image(fill_color="#102A43", back_color="white")  # matches --brand-navy


def build_pdf_report(patient: dict) -> bytes:
    pid = display_id(patient["id"])
    qr_buffer = io.BytesIO()
    _build_qr_image(f"BrainGuard-AI:{pid}").save(qr_buffer, format="PNG")
    qr_buffer.seek(0)

    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(28, 61, 90)
    pdf.cell(0, 12, "BrainGuard AI - Medical Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "AI-assisted dementia risk assessment", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(6)

    pdf.set_draw_color(28, 61, 90)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Patient Information", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    for label, value in [
        ("Patient ID", pid),
        ("Full Name", patient.get("full_name") or "-"),
        ("Gender", patient.get("gender") or "-"),
        ("Age", str(patient.get("age") or "-")),
        ("Registration Date", patient.get("registration_date") or "-"),
    ]:
        pdf.cell(50, 7, label)
        pdf.cell(0, 7, _pdf_safe(value), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    prediction = patient.get("prediction_label")
    confidence = patient.get("confidence")

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Assessment Result", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    for label, value in [
        ("Assessment Type", patient.get("assessment_type") or "-"),
        ("Prediction", prediction or "Not yet assessed"),
        ("Prediction Probability", f"{confidence:.1f}%" if confidence is not None else "-"),
    ]:
        pdf.cell(50, 7, label)
        pdf.cell(0, 7, _pdf_safe(value), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "AI Recommendation", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 7, RECOMMENDATIONS.get(prediction, "No recommendation available yet."))
    pdf.ln(4)

    pdf.image(qr_buffer, x=160, y=pdf.get_y(), w=30)

    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        130, 6,
        "Disclaimer: This report is generated by an educational AI decision-support "
        "tool, not a diagnosis or medical device. A Low Risk result does not rule "
        "out dementia; a High Risk result does not mean the patient has or will "
        "develop dementia. Always consult a qualified physician.",
    )

    return bytes(pdf.output())
